/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    products: Product;
    portfolio: Portfolio;
    customers: Customer;
    orders: Order;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    portfolio: PortfolioSelect<false> | PortfolioSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  category:
    | 'Beds'
    | 'Sofas'
    | 'Dining Tables'
    | 'Coffee & Side Tables'
    | 'Chairs'
    | 'Study Desks'
    | 'Wardrobes & Almirahs'
    | 'Mirrors & Dressing Tables'
    | 'Benches'
    | 'Shoe & Luggage Racks'
    | 'Lamps'
    | 'Custom Orders';
  woodType: 'Sheesham' | 'Teak' | 'Mango Wood' | 'Pine' | 'Walnut' | 'Oak' | 'Ash' | 'Custom';
  price: number;
  dimensions?: string | null;
  summary?: string | null;
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio".
 */
export interface Portfolio {
  id: number;
  title: string;
  category: 'living-room' | 'bedroom' | 'dining' | 'office' | 'custom';
  location?: string | null;
  summary?: string | null;
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  fullName: string;
  phone: string;
  email?: string | null;
  city?: string | null;
  lastInterest?: string | null;
  lastOrderType?: ('enquiry' | 'wishlist' | 'cart') | null;
  lastOrderReference?: string | null;
  lastPaymentMethod?: ('upi' | 'bank-transfer' | 'cash-on-delivery') | null;
  lastPaymentStatus?: ('pending' | 'awaiting-confirmation' | 'paid' | 'failed' | 'refunded') | null;
  notes?: string | null;
  lastEnquiredAt?: string | null;
  lastOrderAt?: string | null;
  totalOrders?: number | null;
  totalSpend?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  reference: string;
  orderType: 'enquiry' | 'wishlist' | 'cart';
  status?:
    | (
        | 'new'
        | 'contacted'
        | 'quoted'
        | 'pending-payment'
        | 'confirmed'
        | 'processing'
        | 'completed'
        | 'cancelled'
        | 'converted'
        | 'closed'
      )
    | null;
  source?: ('website' | 'admin' | 'whatsapp') | null;
  customer?: (number | null) | Customer;
  customerName?: string | null;
  customerPhone?: string | null;
  customerEmail?: string | null;
  customerCity?: string | null;
  customerAddress?: string | null;
  interest?:
    | (
        | 'Beds'
        | 'Sofas'
        | 'Dining Tables'
        | 'Coffee & Side Tables'
        | 'Chairs'
        | 'Study Desks'
        | 'Wardrobes & Almirahs'
        | 'Mirrors & Dressing Tables'
        | 'Benches'
        | 'Shoe & Luggage Racks'
        | 'Lamps'
        | 'Multiple Items'
        | 'Custom Order'
      )
    | null;
  message?: string | null;
  items?:
    | {
        product?: (number | null) | Product;
        productName: string;
        quantity?: number | null;
        price?: number | null;
        /**
         * Calculated automatically from quantity x unit price.
         */
        lineTotal?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Calculated from the line items.
   */
  subtotal?: number | null;
  deliveryCharge?: number | null;
  /**
   * Subtotal plus delivery charges.
   */
  totalAmount?: number | null;
  currency?: string | null;
  paymentMethod?: ('upi' | 'bank-transfer' | 'cash-on-delivery') | null;
  paymentStatus?: ('pending' | 'awaiting-confirmation' | 'paid' | 'failed' | 'refunded') | null;
  paymentReference?: string | null;
  paymentNotes?: string | null;
  paymentCapturedAt?: string | null;
  businessNotes?: string | null;
  whatsappUrl?: string | null;
  submittedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'portfolio';
        value: number | Portfolio;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  woodType?: T;
  price?: T;
  dimensions?: T;
  summary?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio_select".
 */
export interface PortfolioSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  location?: T;
  summary?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  fullName?: T;
  phone?: T;
  email?: T;
  city?: T;
  lastInterest?: T;
  lastOrderType?: T;
  lastOrderReference?: T;
  lastPaymentMethod?: T;
  lastPaymentStatus?: T;
  notes?: T;
  lastEnquiredAt?: T;
  lastOrderAt?: T;
  totalOrders?: T;
  totalSpend?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  reference?: T;
  orderType?: T;
  status?: T;
  source?: T;
  customer?: T;
  customerName?: T;
  customerPhone?: T;
  customerEmail?: T;
  customerCity?: T;
  customerAddress?: T;
  interest?: T;
  message?: T;
  items?:
    | T
    | {
        product?: T;
        productName?: T;
        quantity?: T;
        price?: T;
        lineTotal?: T;
        id?: T;
      };
  subtotal?: T;
  deliveryCharge?: T;
  totalAmount?: T;
  currency?: T;
  paymentMethod?: T;
  paymentStatus?: T;
  paymentReference?: T;
  paymentNotes?: T;
  paymentCapturedAt?: T;
  businessNotes?: T;
  whatsappUrl?: T;
  submittedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  themeSettings?: {
    colorTheme?: ('heritage' | 'forest' | 'charcoal') | null;
    fontPairing?: ('classic' | 'modern' | 'editorial') | null;
  };
  /**
   * Controls the static text, images, gallery, video, and process sections on the homepage.
   */
  homePage?: {
    hero?: {
      eyebrow?: string | null;
      titleLine1?: string | null;
      titleLine2?: string | null;
      titleLine3?: string | null;
      description?: string | null;
      primaryCtaLabel?: string | null;
      secondaryCtaLabel?: string | null;
      statsText?: string | null;
      /**
       * Used as the first hero/background image.
       */
      beforeImage?: (number | null) | Media;
      /**
       * Used as the second hero/background image in the reveal animation.
       */
      afterImage?: (number | null) | Media;
    };
    gallery?: {
      eyebrow?: string | null;
      heading?: string | null;
      description?: string | null;
      items?:
        | {
            image?: (number | null) | Media;
            title: string;
            detail?: string | null;
            size?: ('normal' | 'large' | 'tall' | 'wide') | null;
            id?: string | null;
          }[]
        | null;
    };
    portfolio?: {
      eyebrow?: string | null;
      heading?: string | null;
      description?: string | null;
      videoTitle?: string | null;
      /**
       * Upload MP4/WebM videos in Media.
       */
      videoFile?: (number | null) | Media;
      videoPoster?: (number | null) | Media;
      /**
       * Optional YouTube/Vimeo URL. Used when no video file is selected.
       */
      videoEmbedUrl?: string | null;
    };
    whyChooseUs?: {
      eyebrow?: string | null;
      heading?: string | null;
      description?: string | null;
      items?:
        | {
            icon?: ('wood' | 'hands' | 'ruler' | 'truck' | 'leaf' | 'chat') | null;
            title: string;
            body: string;
            id?: string | null;
          }[]
        | null;
    };
    about?: {
      eyebrow?: string | null;
      heading?: string | null;
      image?: (number | null) | Media;
      paragraphs?:
        | {
            text: string;
            id?: string | null;
          }[]
        | null;
      stats?:
        | {
            value: number;
            suffix?: string | null;
            label: string;
            id?: string | null;
          }[]
        | null;
    };
    process?: {
      eyebrow?: string | null;
      heading?: string | null;
      description?: string | null;
      steps?:
        | {
            number: string;
            title: string;
            body: string;
            id?: string | null;
          }[]
        | null;
    };
    contact?: {
      eyebrow?: string | null;
      heading?: string | null;
      description?: string | null;
      workingHours?: string | null;
      /**
       * Optional Google Maps embed URL for the contact map area.
       */
      mapEmbedUrl?: string | null;
    };
    /**
     * Showcase completed projects and past work on the website.
     */
    previousWork?: {
      eyebrow?: string | null;
      heading?: string | null;
      description?: string | null;
      /**
       * Add, remove, reorder, or edit previous work items here.
       */
      items?:
        | {
            image?: (number | null) | Media;
            title: string;
            category?: ('bedroom' | 'living-room' | 'dining' | 'office' | 'outdoor' | 'custom') | null;
            /**
             * City or area where this project was delivered.
             */
            location?: string | null;
            /**
             * Year of completion, e.g. 2025.
             */
            year?: string | null;
            description?: string | null;
            id?: string | null;
          }[]
        | null;
    };
  };
  testimonialSection?: {
    eyebrow?: string | null;
    heading?: string | null;
    /**
     * Admins can add, remove, reorder, or edit homepage testimonials here.
     */
    items?:
      | {
          quote: string;
          author: string;
          rating?: number | null;
          id?: string | null;
        }[]
      | null;
  };
  whatsappNumber: string;
  displayPhone: string;
  contactEmail: string;
  instagramUrl: string;
  instagramHandle: string;
  workshopAddress: string;
  paymentSettings?: {
    acceptUpi?: boolean | null;
    upiId?: string | null;
    acceptBankTransfer?: boolean | null;
    bankAccountName?: string | null;
    bankName?: string | null;
    bankAccountNumber?: string | null;
    bankIfsc?: string | null;
    acceptCashOnDelivery?: boolean | null;
    paymentInstructions?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  themeSettings?:
    | T
    | {
        colorTheme?: T;
        fontPairing?: T;
      };
  homePage?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              titleLine1?: T;
              titleLine2?: T;
              titleLine3?: T;
              description?: T;
              primaryCtaLabel?: T;
              secondaryCtaLabel?: T;
              statsText?: T;
              beforeImage?: T;
              afterImage?: T;
            };
        gallery?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              items?:
                | T
                | {
                    image?: T;
                    title?: T;
                    detail?: T;
                    size?: T;
                    id?: T;
                  };
            };
        portfolio?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              videoTitle?: T;
              videoFile?: T;
              videoPoster?: T;
              videoEmbedUrl?: T;
            };
        whyChooseUs?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              items?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    body?: T;
                    id?: T;
                  };
            };
        about?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              image?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              stats?:
                | T
                | {
                    value?: T;
                    suffix?: T;
                    label?: T;
                    id?: T;
                  };
            };
        process?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              steps?:
                | T
                | {
                    number?: T;
                    title?: T;
                    body?: T;
                    id?: T;
                  };
            };
        contact?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              workingHours?: T;
              mapEmbedUrl?: T;
            };
        previousWork?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              items?:
                | T
                | {
                    image?: T;
                    title?: T;
                    category?: T;
                    location?: T;
                    year?: T;
                    description?: T;
                    id?: T;
                  };
            };
      };
  testimonialSection?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        items?:
          | T
          | {
              quote?: T;
              author?: T;
              rating?: T;
              id?: T;
            };
      };
  whatsappNumber?: T;
  displayPhone?: T;
  contactEmail?: T;
  instagramUrl?: T;
  instagramHandle?: T;
  workshopAddress?: T;
  paymentSettings?:
    | T
    | {
        acceptUpi?: T;
        upiId?: T;
        acceptBankTransfer?: T;
        bankAccountName?: T;
        bankName?: T;
        bankAccountNumber?: T;
        bankIfsc?: T;
        acceptCashOnDelivery?: T;
        paymentInstructions?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}