import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-sqlite'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.run(sql`ALTER TABLE \`customers\` ADD \`last_order_type\` text;`)
  await db.run(sql`ALTER TABLE \`customers\` ADD \`last_order_reference\` text;`)
  await db.run(sql`ALTER TABLE \`customers\` ADD \`last_payment_method\` text;`)
  await db.run(sql`ALTER TABLE \`customers\` ADD \`last_payment_status\` text;`)
  await db.run(sql`ALTER TABLE \`customers\` ADD \`last_order_at\` text;`)
  await db.run(sql`ALTER TABLE \`customers\` ADD \`total_orders\` numeric DEFAULT 0;`)
  await db.run(sql`ALTER TABLE \`customers\` ADD \`total_spend\` numeric DEFAULT 0;`)
  await db.run(sql`ALTER TABLE \`orders_items\` ADD \`line_total\` numeric;`)
  await db.run(sql`ALTER TABLE \`orders\` ADD \`customer_address\` text;`)
  await db.run(sql`ALTER TABLE \`orders\` ADD \`subtotal\` numeric;`)
  await db.run(sql`ALTER TABLE \`orders\` ADD \`delivery_charge\` numeric DEFAULT 0;`)
  await db.run(sql`ALTER TABLE \`orders\` ADD \`total_amount\` numeric;`)
  await db.run(sql`ALTER TABLE \`orders\` ADD \`currency\` text DEFAULT 'INR';`)
  await db.run(sql`ALTER TABLE \`orders\` ADD \`payment_method\` text;`)
  await db.run(sql`ALTER TABLE \`orders\` ADD \`payment_status\` text;`)
  await db.run(sql`ALTER TABLE \`orders\` ADD \`payment_reference\` text;`)
  await db.run(sql`ALTER TABLE \`orders\` ADD \`payment_notes\` text;`)
  await db.run(sql`ALTER TABLE \`orders\` ADD \`payment_captured_at\` text;`)
  await db.run(sql`ALTER TABLE \`orders\` ADD \`business_notes\` text;`)
  await db.run(sql`ALTER TABLE \`site_settings\` ADD \`payment_settings_accept_upi\` integer DEFAULT true;`)
  await db.run(sql`ALTER TABLE \`site_settings\` ADD \`payment_settings_upi_id\` text DEFAULT 'payments@deeksha';`)
  await db.run(sql`ALTER TABLE \`site_settings\` ADD \`payment_settings_accept_bank_transfer\` integer DEFAULT true;`)
  await db.run(sql`ALTER TABLE \`site_settings\` ADD \`payment_settings_bank_account_name\` text DEFAULT 'Deeksha Handicrafts';`)
  await db.run(sql`ALTER TABLE \`site_settings\` ADD \`payment_settings_bank_name\` text DEFAULT 'Your Bank Name';`)
  await db.run(sql`ALTER TABLE \`site_settings\` ADD \`payment_settings_bank_account_number\` text DEFAULT '1234567890';`)
  await db.run(sql`ALTER TABLE \`site_settings\` ADD \`payment_settings_bank_ifsc\` text DEFAULT 'BANK0001234';`)
  await db.run(sql`ALTER TABLE \`site_settings\` ADD \`payment_settings_accept_cash_on_delivery\` integer DEFAULT true;`)
  await db.run(sql`ALTER TABLE \`site_settings\` ADD \`payment_settings_payment_instructions\` text DEFAULT 'Share your order reference after payment so we can confirm your build slot and delivery timeline.';`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.run(sql`ALTER TABLE \`customers\` DROP COLUMN \`last_order_type\`;`)
  await db.run(sql`ALTER TABLE \`customers\` DROP COLUMN \`last_order_reference\`;`)
  await db.run(sql`ALTER TABLE \`customers\` DROP COLUMN \`last_payment_method\`;`)
  await db.run(sql`ALTER TABLE \`customers\` DROP COLUMN \`last_payment_status\`;`)
  await db.run(sql`ALTER TABLE \`customers\` DROP COLUMN \`last_order_at\`;`)
  await db.run(sql`ALTER TABLE \`customers\` DROP COLUMN \`total_orders\`;`)
  await db.run(sql`ALTER TABLE \`customers\` DROP COLUMN \`total_spend\`;`)
  await db.run(sql`ALTER TABLE \`orders_items\` DROP COLUMN \`line_total\`;`)
  await db.run(sql`ALTER TABLE \`orders\` DROP COLUMN \`customer_address\`;`)
  await db.run(sql`ALTER TABLE \`orders\` DROP COLUMN \`subtotal\`;`)
  await db.run(sql`ALTER TABLE \`orders\` DROP COLUMN \`delivery_charge\`;`)
  await db.run(sql`ALTER TABLE \`orders\` DROP COLUMN \`total_amount\`;`)
  await db.run(sql`ALTER TABLE \`orders\` DROP COLUMN \`currency\`;`)
  await db.run(sql`ALTER TABLE \`orders\` DROP COLUMN \`payment_method\`;`)
  await db.run(sql`ALTER TABLE \`orders\` DROP COLUMN \`payment_status\`;`)
  await db.run(sql`ALTER TABLE \`orders\` DROP COLUMN \`payment_reference\`;`)
  await db.run(sql`ALTER TABLE \`orders\` DROP COLUMN \`payment_notes\`;`)
  await db.run(sql`ALTER TABLE \`orders\` DROP COLUMN \`payment_captured_at\`;`)
  await db.run(sql`ALTER TABLE \`orders\` DROP COLUMN \`business_notes\`;`)
  await db.run(sql`ALTER TABLE \`site_settings\` DROP COLUMN \`payment_settings_accept_upi\`;`)
  await db.run(sql`ALTER TABLE \`site_settings\` DROP COLUMN \`payment_settings_upi_id\`;`)
  await db.run(sql`ALTER TABLE \`site_settings\` DROP COLUMN \`payment_settings_accept_bank_transfer\`;`)
  await db.run(sql`ALTER TABLE \`site_settings\` DROP COLUMN \`payment_settings_bank_account_name\`;`)
  await db.run(sql`ALTER TABLE \`site_settings\` DROP COLUMN \`payment_settings_bank_name\`;`)
  await db.run(sql`ALTER TABLE \`site_settings\` DROP COLUMN \`payment_settings_bank_account_number\`;`)
  await db.run(sql`ALTER TABLE \`site_settings\` DROP COLUMN \`payment_settings_bank_ifsc\`;`)
  await db.run(sql`ALTER TABLE \`site_settings\` DROP COLUMN \`payment_settings_accept_cash_on_delivery\`;`)
  await db.run(sql`ALTER TABLE \`site_settings\` DROP COLUMN \`payment_settings_payment_instructions\`;`)
}
